server:
  port: 10118

# application-db.yml
spring:
  profiles:
    include: db
  messages:
    basename: messages.messages,config.i18n.messages
    encoding: utf-8

  #  jpa:
  #    database: mysql
  #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #    hibernate:
  #      ddl-auto: none


  # after update html, not restart server

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true