server:
  port: 10118

# application-db.yml
spring:
  profiles:
    include: db

#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: none


# after update html, not restart server

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false

#쿼리 로그
decorator:
  datasource:
    p6spy:
      enable-logging: true


